### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by andykais** [DeadSix27/waifu2x-converter-cpp#260]
program output:
```
 andrew  Gash Bell  video2x -i gash-bell-01.mp4 -o gash-bell-01-video2x-upscaled.mp4 -d waifu2x_converter_cpp

    __      __  _       _                  ___   __   __
    \ \    / / (_)     | |                |__ \  \ \ / /
     \ \  / /   _    __| |   ___    ___      ) |  \ V /
      \ \/ /   | |  / _` |  / _ \  / _ \    / /    > <
       \  /    | | | (_| | |  __/ | (_) |  / /_   / . \
        \/     |_|  \__,_|  \___|  \___/  |____| /_/ \_\


                  Video2X Video Enlarger

                       Version 4.3.1

[+] INFO: Loading files into processing queue
2021-01-09 01:27:13.381276 [+] INFO: Input path(s): gash-bell-01.mp4
2021-01-09 01:27:13.384383 [+] INFO: File MIME type: video/mp4
[+] INFO: Loaded files into processing queue
2021-01-09 01:27:13.387066 [+] INFO: Input file: /media/Torrents/Gash Bell/gash-bell-01.mp4
[+] INFO: Reading file information
2021-01-09 01:27:13.387229 [+] INFO: Executing: /usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -i /media/Torrents/Gash Bell/gash-bell-01.mp4
2021-01-09 01:27:13.434903 [+] INFO: Creating cache directory /var/tmp/video2x
2021-01-09 01:27:13.435306 [+] INFO: Extracted frames are being saved to: /var/tmp/video2x/tmpyn2l2ib9
2021-01-09 01:27:13.435417 [+] INFO: Upscaled frames are being saved to: /var/tmp/video2x/tmpm2a4z66l
[+] INFO: Starting upscaling video/GIF
[+] INFO: Getting total number of frames in the file
[+] INFO: Calculating scaling parameters
None None 480 640
Cleaning up cache directory: /var/tmp/video2x/tmpyn2l2ib9
Cleaning up cache directory: /var/tmp/video2x/tmpm2a4z66l
Cleaning up cache directory: /var/tmp/video2x
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "/usr/bin/video2x", line 342, in <module>
    upscaler.run()
  File "/usr/share/video2x/upscaler.py", line 1023, in run
    raise e
  File "/usr/share/video2x/upscaler.py", line 737, in run
    output_width = output_height / height * width
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
[!] ERROR: The error log file can be found at: /tmp/video2x_xoelpc20.log
```
```
 andrew  ~  waifu2x-converter-cpp --version
waifu2x-converter-cpp  version: v5.3.3 (master-27ad20e)
```

running arch linux on a laptop with intel integrated graphics

**Comment by andykais** [comment]
Apologies, disregard. Opened in the wrong repo :sweat_smile:
